---
title: "Treatment-Seeking"
weight: 1
format: 
  html:
    toc: true
    toc-depth: 5
    page-layout: full
execute: 
  enabled: false 
---

Management of symptomatic cases

# Case Management/Treatment-Seeking

Case management is controlled in EMOD by an [`add_treatment_seeking()`](https://github.com/numalariamodeling/emodpy-malaria/blob/main/emodpy_malaria/interventions/treatment_seeking.py) function within emodpy-malaria. This function is a node level intervention that allows you to target individuals on the node for malaria treatment through treatment seeking behavior. 

In this example, treatment is triggered by new cases and codes for differences in case management coverage between individuals of age 0-5 yrs and 5-100yrs as set by the two trigger dictionaries' respective `agemin` and `agemax`. Importantly, we distinguish between `NewClinicalCase` and `NewSevereCase` to provide slightly different case management for uncomplicated and severe cases. In the example below, the main differences for these types of case management are seen in coverage level and the rate of receiving treatment after seeking care, `rate`. This `rate` is used to create an exponential distribution of the delay period. We usually set `rate = 1/3` for clinical cases and `rate = 1/2.` for severe cases.

The `seek` argument dictates the proportion of people who will seek care with a new clinical case - it is usually set to 1 such that `coverage` is the true case management coverage level. 

You can also specify which drugs are used for case management. The default is Artemether-Lumefantrine with age-based dosing. Pre-configured drugs can be viewed in the `emodpy-malaria` repositry [here](https://github.com/numalariamodeling/emodpy-malaria/blob/main/emodpy_malaria/malaria_drug_params.csv).

Additional parameters can be added to restrict case management to certain nodes, node properties, or individual properties. See [here](https://docs.idmod.org/projects/emodpy-malaria/en/latest/emodpy_malaria.interventions.treatment_seeking.html) for more information.


```{python}
import emod_api.campaign as camp
import emodpy_malaria.interventions.treatment_seeking as cm

cm.add_treatment_seeking(camp, start_day=0, drug=['Artemether', 'Lumefantrine'],
                         targets=[{'trigger': 'NewClinicalCase', 
                                   'coverage': 0.7, 'agemin': 0, 'agemax': 5,
                                   'seek': 1,'rate': 0.3},
                                 {'trigger': 'NewClinicalCase', 
                                  'coverage': 0.5, 'agemin': 5, 'agemax': 100,
                                  'seek': 1,'rate': 0.3},
                                 {'trigger': 'NewSevereCase', 
                                  'coverage': 0.85, 'agemin': 0, 'agemax': 100,
                                  'seek': 1,'rate': 0.5}],
                         broadcast_event_name="Received_Treatment")
```
