---
title: "Expectations for Journal Club"
weight: 6
format: 
  html: 
    toc: true
    toc-depth: 5
---
[[Back to Best Practices](../nu_team_best_practices.qmd)<br>[Back to Journal Club](../../../../resources/articles/journal_club.qmd)]{.aside}

Expectations for participating in Journal Club as a leader or discussant

### Objectives of the applied modeling journal club

Through reading and discussing this series of papers, program participants will be introduced to the field of applied malaria modeling. Participants will see past applications of EMOD as well as a few other individual-based models that have been used to inform policy. The chosen papers reflect a wide range of topics such that participants will be exposed to different model capabilities.

Even if a particular paper is of limited relevance to someone's project, each paper and discussion is an opportunity to practice critical reading. Where did the model do well? What were its limitations? Was the approach rigorous? Did the results make sense, and were they presented clearly? Was the model fit for purpose? These are all questions we need to ask of ourselves in our own applied modeling work. Journal Club lets us practice thinking through how to answer these questions together.

### Guidance for leaders

Journal club leaders are expected to be able to walk discussants through the paper, explaining the following on the *content* of the paper:  

* Motivation for the work  
* Approach used  
* Walk through each figure, including methods and results  
* Main conclusions  

Journal club leaders should also have prepared their own thoughts on the *analysis* of the paper:  

* Strengths and limitations of the model  
* To what extent the conclusions are supported by the results  
* What further evidence would support the modeling results  
* What would be other interesting questions to ask, using either the approach in the paper or other approaches (modeling or not)

#### Before

* Read the assigned paper at least 3 days prior to the session
* Prepare answers to the content and analysis points above and note anything confusing
* Discuss answers with buddy and clarify points of confusion

#### During

* Lead everyone through reviewing the content of the paper, making sure everyone understood what was done and why
* Lead everyone through a discussion of the analysis of the paper, covering each of the analysis points listed above, and bringing in new questions and ideas
* Manage the discussion so everyone contributes and no one dominates
* Manage the overall pace such that the entirety of the paper and the discussion points are covered

#### After

* Follow up on any questions raised during the discussion that could not be answered at the time

### Guidance for discussants

#### Before

* Read the assigned paper prior to attending the journal club session
* Make notes and mark any questions you may have to discuss with the group

#### During

* Be an active participant so we can all learn from each other's ideas
* If you have a question, others will too. We are here to learn
