---
title: "Conduct, Ethics, and Team Culture"
weight: 1
format: 
  html: 
    toc: true
    toc-depth: 5
---

General conduct, ethics, engagement, professional critique, and teamwork

#### General conduct

All members of the team, along with visitors, are expected to abide by this code of conduct. I expect cooperation from all members to help ensure a safe environment for everybody. This team is dedicated to providing a harassment-free experience for everyone, regardless of gender, gender identity and expression, age, sexual orientation, disability, physical appearance, body size, race, or religion (or lack thereof). We do not tolerate harassment of team members in any form. Harassment can include offensive verbal comments, sexual images in public spaces, deliberate intimidation, stalking, following, harassing photography or recording, sustained disruption of talks or other events, inappropriate physical contact, and unwelcome sexual attention. Members asked to stop any harassing behavior are expected to comply immediately. We expect members to follow these guidelines in all in person, phone, online communication, team-related events, university events, conferences, etc. If you are being harassed, notice that someone else is being harassed, or have any other concerns, please contact Jaline immediately. Please note that Jaline is a mandatory reporter, this means that she is required to report sexual misconduct to the Title IX office and may not be able to guarantee confidentiality.

#### Ethical conduct of research

I expect team members to be honest in scientific communications both within and outside the team. I expect that credit will be given where credit is due, including in scientific writing. It is never okay to tamper with data, make up data, omit data, or fudge results in any way, and this will not be tolerated. Science is about finding out the truth, not about fitting a hypothesis or data that looks pretty. My goal is for our team to have a reputation for performing impeccably rigorous science in an open and transparent way.

#### Culture of engagement and professional critique

We would like to foster a highly engaged research environment where everyone is included in discussions and professional critique is welcome. You are expected to think critically about your own work as well as others’ work, and to express your questions and opinions politely and professionally. Our aim for your time with the team is to grow your independence and for everyone to do great work --- we are stronger when we give each other feedback and seriously consider each other’s suggestions. This includes giving me feedback on what you think I can do better and pointing out my blind spots. I will not penalize you for disagreeing with me but will be glad you’re speaking up.

#### Culture of teamwork

We work on an incredibly important health problem that affects millions of people, and the faster we can work the sooner we can have a positive impact. This means that I don’t want you to spend weeks bashing your head against a problem if talking to someone else would mean it gets resolved more quickly. Think about where you add the most value: is it building software? Designing experiments? Thinking about science? Communicating with our partners? Lean into your strengths and let the team help you with other aspects of your work.