---
title: "Team Communication"
weight: 2
format: 
  html: 
    toc: true
    toc-depth: 5
---

How to stay informed and ask for help

### Slack

Slack is the preferred method of electronic communication on our team. Generally, team members are expected to respond to one another within 24 hours (within normal working hours). You are welcome to join any of the Slack channels; some are more active than others.

You are expected to be on Slack when you are working. Slack will be the primary means of communication with NU team members. You can join any channel on slack or start a new one - but these are some of the most often-used:

#### Chicago Channel

* Post daily “to-do list” of tasks you’re working on  
*	Keep an eye out for team-wide announcements

#### FE 2023 Channel

*	Announcements and questions specific to the Faculty Enrichment Program should be posted here by both staff and participants  
*	Feel free to share outputs, items of interest, or other things relating to the program – this is your space!

#### Help Channel

*	Post error messages / other issues here (along with your code & relevant outputs). You’re more likely to get a quick response, and others will benefit from seeing the solution too. 

#### Celebrations Channel

*	Proud of an accomplishment (program-related or otherwise)? Post it here so we can celebrate with you!

### University email

You should be given access to a Northwestern email account and are free to use it as you see fit. However, it may be best to use a personal or home institution email for longevity of communications as NU email access may be limited after the program end. 

Northwestern University administrators will use your Northwestern email for official communication, so make sure to check it occasionally.


### Calendars

All meeting invites will be shared with you in advance – please be sure to stay on top of your calendar and attend all meetings in a timely fashion.

### Meetings

#### Meetings with your buddy

Weekly 1-on-1 meetings will be held with your assigned buddy. These are designed to help you stay on track with learning materials and your project. You may use this time as you see fit but it is recommended that you discuss any problems you may be encountering in your work, results, next steps, and other questions. You and your assigned buddy will discuss any additional expectations during your first sessions to make the best use of this time.

#### Meetings with Jaline

Weekly 1-on-1 meetings will also be held with Jaline to discuss project progress, ideas, and needs. This meeting will be similar to buddy 1-on-1s and sometimes may be held together as a 2-on-1 to ensure that you are getting the best support possible throughout the program and everyone is on the same page. It is your responsibility to make the most of your meetings with Jaline, which includes being prepared with what you would like to discuss.

**Jaline’s meeting policy:**

In general, I have an open-door policy. If my office door is open, I am happy to answer questions or talk about your work---if I don’t want to be disturbed, I will close my door. Please ping me on Slack at any time and I will respond as soon as I can. However, I am not always available, so if there is something important that will take a substantial time to discuss, it is best to schedule a meeting with me.

What should you bring to a meeting with me? It is your job to make the most of this time and usually that means coming in with a list of what you’d like to talk about. Here is what we will generally cover:  
* What you have done: Generally I prefer that you keep me/the group posted on new analyses via Slack. But the 1-on-1 is also a good time to talk over interesting results or roadblocks: What analyses have you done since the last time we met? I want to see all your new results, analyzed and in pretty graphs. We may also take a deeper dive to look at individual results or brainstorm new analyses, so bring that with you. If you don’t have results, why not? What roadblocks are you facing and how are you working through them? What analyses or simulations are in progress? How are writing projects coming along? I am asking for this information not to evaluate if you are working hard enough, but to see how your project is progressing.  
* Ideas: what do your results mean? What should we do next? Do we have what we need to do it?  
*	What do you need from me? This is the time to let me know if you need a signature, a letter of recommendation, a progress report, extra compute resources, or new software.  
*	Anything pertinent to your professional development or well-being. Are you progressing towards your goals for the program? If there are any issues in or outside of the workplace that may hinder your progress, this is a time to talk about it.  

I strongly recommend you keep a log of your weekly 1-on-1’s, noting what was discussed and any next steps you’re planning to do.


### Getting help

#### Office Hours

#### Logistics
