---
title: "Writing Standards"
weight: 1
format: 
  html: 
    toc: true
    toc-depth: 5
---

Best writing practices for manuscripts and grants

## General 

### Peer Editing Hour

#### For Authors

Come prepared with ~1 page of writing. Please send this to Shannon by the 9am CT the day of your peer editing session so she can ensure everything is in the right format to share with the team. Ideally, your writing should be in decent shape (i.e. not a messy first draft) by the time you are sharing it with the team. Be prepared to introduce your piece (context, audience, etc) and read your writing aloud to the group, one paragraph at a time, and receive feedback as we go. The facilitator will document comments and changes to the text for you. You may receive feedback on writing style, word choice, sentence structure, grammar, general comments and questions about the work, etc. This time is meant to be constructive and help you improve your final product, so please make the best use of it possible.

#### For Facilitators

You will be responsible for documenting any changes, suggestions, or comments on the work presented – you do not need to be familiar with the work in advance. At the beginning of the hour, make sure that the document is in “track changes” mode so the author will be able to easily see anything that has been modified when looking back at their work. Please be detailed in recording all comments so they can be as useful as possible. 

#### For Audience

Bring your best constructive criticism and writing ideas! Be open to sharing your thoughts, big and small, to help your colleagues improve their writing. Authors may present work in various stages of development and/or completeness so ask clarifying questions as needed. This may be especially relevant for excerpts from specific sections of manuscripts where you may not understand the context or what has already been discussed (e.g. what is included in the first half of the background/introduction while we are editing the second half). Be sure to consider any information provided by the author when introducing their writing, such as the intended audience.

### Writing Collaboratively


## Writing Grant Applications

### Specific Aims 

### Investigator "Biosketch"

## Writing Manuscripts





