---
title: "EMOD Papers"
weight: 1
page-layout: article
format:
  html:
    toc: true
    toc-depth: 5
---


### Official EMOD Documentation

[IDM Documentation](https://docs.idmod.org/projects/emod-malaria/en/latest/index.html)

### Software Design of EMOD

(**2018**) [Implementation and applications of EMOD, an individual-based multi-disease modeling platform](https://doi.org/10.1093/femspd/fty059)

(**2018**) [Agent-based models of malaria transmission: a systematic review](https://malariajournal.biomedcentral.com/articles/10.1186/s12936-018-2442-y)

### Mosquito Model

(**2011**) [A malaria transmission-directed model of mosquito life cycle and ecology](https://link.springer.com/article/10.1186/1475-2875-10-303)

### Within-Host Model

(**2012**) [P. falciparum Infection Durations and Infectiousness Are Shaped by Antigenic Variation and Innate and Adaptive Host Immunity in a Mathematical Model](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0044950)

(**2012**) [Malaria parasite diversity and transmission intensity affect development of parasitological immunity in a mathematical model](https://link.springer.com/article/10.1186/1475-2875-11-419)

(**2021**) [Mechanistic within-host models of the asexual Plasmodium falciparum infection: a review and analytical assessment](https://malariajournal.biomedcentral.com/articles/10.1186/s12936-021-03813-z)

### Within-Host Calibration and Transmission

(**2015**) [Calibration of an intrahost malaria model and parameter ensemble evaluation of a pre-erythrocytic vaccine](https://malariajournal.biomedcentral.com/articles/10.1186/1475-2875-14-6)

(**2015**) [Characterization of the infectious reservoir of malaria with an agent-based model calibrated to age-stratified parasite densities and infectiousness](https://malariajournal.biomedcentral.com/articles/10.1186/s12936-015-0751-y)

(**2018**) [Seasonality and heterogeneity of malaria transmission determine success of interventions in high-endemic settings: a modeling study](https://bmcinfectdis.biomedcentral.com/articles/10.1186/s12879-018-3319-y)

(**2018**) [Modeling the impact of Plasmodium falciparum sexual stage immunity on the composition and dynamics of the human infectious reservoir for malaria in natural settings](https://journals.plos.org/plospathogens/article?id=10.1371/journal.ppat.1007034)


### Interventions

#### Generic Interventions

(**2013**) [Mathematical Models of Within-Host and Transmission Dynamics to Determine Effects of Malaria Interventions in a Variety of Transmission Settings](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3752743/)

#### Drug-Based Interventions

(**2015**) [Mass campaigns with antimalarial drugs: a modelling comparison of artemether-lumefantrine and DHA-piperaquine with and without primaquine as tools for malaria control and elimination](https://bmcinfectdis.biomedcentral.com/articles/10.1186/s12879-015-0887-y)

(**2017**) [Role of mass drug administration in elimination of Plasmodium falciparum malaria: a consensus modelling study](https://www.thelancet.com/journals/langlo/article/PIIS2214-109X(17)30220-6/fulltext)

(**2018**) [Impact of mass drug administration campaigns depends on interaction with seasonal human movement](https://academic.oup.com/inthealth/article/10/4/252/4965024?login=true)

(**2019**) [Reducing malaria burden and accelerating elimination with long-lasting systemic insecticides: a modelling study of three potential use cases](https://malariajournal.biomedcentral.com/articles/10.1186/s12936-019-2942-4)

#### Vaccines

(**2013**) [A mathematical model of the impact of present and future malaria vaccines](https://malariajournal.biomedcentral.com/articles/10.1186/1475-2875-12-126)

(**2016**) [Public health impact and cost-effectiveness of the RTS,S/AS01 malaria vaccine: a systematic comparison of predictions from four mathematical models](https://www.sciencedirect.com/science/article/pii/S0140673615007254)

#### Gene Drives

(**2016**) [Impact of mosquito gene drive on malaria elimination in a computational model with explicit spatial and temporal dynamics](https://www.pnas.org/doi/abs/10.1073/pnas.1611064114)

(**2020**) [Modeling impact and cost-effectiveness of driving-Y gene drives for malaria elimination in the Democratic Republic of the Congo](https://onlinelibrary.wiley.com/doi/10.1111/eva.13331)

(**2021**) [Vector genetics, insecticide resistance and gene drives: An agent-based modeling approach to evaluate malaria transmission and elimination](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1008121)

### Zambia Elimination (Multi-Intervention)

(**2016**) [Optimal Population-Level Infection Detection Strategies for Malaria Control and Elimination in a Spatial Model of Malaria Transmission](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1004707)

(**2016**) [Malaria Elimination Campaigns in the Lake Kariba Region of Zambia: A Spatial Dynamical Model](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1005192)

(**2017**) [Effectiveness of reactive case detection for malaria elimination in three archetypical transmission settings: a modelling study](https://malariajournal.biomedcentral.com/articles/10.1186/s12936-017-1903-z)

(**2019**) [Effective strategies for preventing reestablishment of malaria in areas with recent elimination and high transmission potential](https://www.biorxiv.org/content/10.1101/766048v1.abstract)
