---
title: "2023 Program Handbook"
listing:
  id: "expectations"
  contents: 
    - ../../../expectations/*.qmd
    - best_practices/best_practices_journal_club.qmd
  type: grid
  grid-columns: 3
  fields: [title]
weight: 2
format: 
  html: 
    toc: true
    toc-depth: 5
    
page-layout: article
---

A comprehensive guide to this year's curriculum, assignments, and learning objectives

### Expectations

:::{#expectations}
:::

### Program Milestones

| Week | Milestone                       | Due                    |
|------|---------------------------------|------------------------|
| 0    | Pre-Program Coding Assignment   | **June 23, 2023**      |
| 2    | Introductory Research Talk      | **June 29, 2023**       |
| 2    | Specific Aims Ideas             | **July 7, 2023**       |
| 3    | Specific Aims Outline #1        | **July 14, 2023**      |
| 4    | Specific Aims Outline #2        | **July 21, 2023**      |
| 6    | Specific Aims Full Draft #1     | **July 31, 2023**      |
| 6    | Specific Aims Presentation      | **August 2, 2023**     |
| 8    | Specific Aims Full Draft #2     | **August 18, 2023**    |
| 10   | Specific Aims Full Draft #3     | **September 1, 2023**  |
| 11   | Work-in-Progress Presentation   | **September 6, 2023**  |
| 12   | Specific Aims Peer Editing Hour | **September 13, 2023** |
| 12   | Biosketch Draft #1              | **September 15, 2023** |
| 13   | Specific Aims Full Draft #4     | **September 22, 2023** |
| 14   | Biosketch Draft #2              | **September 29, 2023** |
| 15   | Specific Aims Final Draft       | **October 6, 2023**    |
| 16   | Biosketch Peer Editing Hour     | **October 11, 2023**   |
| 18   | Final Project Presentation      | **October 26, 2023**   |

### Full 2023 Program Handbook
