---
title: "Aims Page Expectations"
weight: 1
format: 
  html: 
    toc: true
    toc-depth: 5
---


### Ideas List

* A list of at least 3 topics or research ideas for your EMOD project in applied malaria modeling  
* **Who will review:**

### Outline Draft 1

* Draft 2-3 specific aims for two of your applied malaria modeling ideas, along with the appropriate context and motivation as bullet points  
* **Who will review:**

### Outline Draft 2

* Pick one of your applied malaria modeling ideas
* Complete the "structure of an aims page" outline for this idea, filling in each element. For elements where you are not sure how to complete, review with one of the instructional staff  
* **Who will review:**

### Full Draft 1

* Using your "structure of an aims page" outline, write the entire first draft of the Aims page, including all sections.  
* **Who will review:**

### Full Drafts 2-4

* Each new draft should be incorporate the feedback you received on the previous draft and anything new you have learned from the program, from literature review, or from executing the project. If you have chosen to reject a piece of feedback, provide a reason. If you need to change topics entirely, do so by returning to the *Outline Draft 2* step and moving forward from there with the new research question.  
* **Who will review:**

### Final Draft

* This should be a very polished Specific Aims page on your applied malaria project that you would be proud to submit to a funding agency.  
* **Who will review:**
