---
title: "Journal Club 2: Seasonality of Transmission and Interventions"
author: 
  -  Selvaraj, P. 
  -  Wenger, E.A. 
  -  Gerardin, J.
doi: https://doi.org/10.1186/s12879-018-3319-y
page-layout: article
---
[[Back to Journal Club](../journal_club.qmd)]{.aside}

**Seasonality and heterogeneity of malaria transmission determine success of interventions in high-endemic settings: a modeling study**

**Context**: Last week we discussed the importance of calibrating models to match what has been observed in the “real world”. Sometimes, however, fundamental quantities underpinning malaria transmission (mosquito populations, immunity levels, etc.) are essentially impossible to measure. For journal club this week, we’ll discuss an article in which the authors leverage EMODs acquired immunity model and use seasonal parasite densities to capture transmission trends despite limited entomological data.

Please read the journal club paper and come prepared to discuss your thoughts. If you are facilitating the
session, prepare an overview of the paper and at least four guiding questions.

**Leader**:

#### Learning Objectives

*  Describe the importance of capturing transmission levels and seasonality in model setup  
*  Understand how seasonality and transmission can impact malaria interventions

#### Guiding Questions

1.  
2.  
3.  
4. 




#### Recommended additional reading

-   Nikolov, M., Bever, C. A., Upfill-Brown, A., Hamainza, B., Miller, J. M., Eckhoff, P. A., ... & Gerardin, J. (2016). [Malaria elimination campaigns in the Lake Kariba region of Zambia: a spatial dynamical model](https://doi.org/10.1371/journal.pcbi.1005192). PLoS computational biology, 12(11), e1005192.