---
title: "Journal Club 0: Use of Mathematical Modeling in WHO Guidelines"
author: 
  -  Lo, N. C. 
  -  Andrejko, K.
  -  Shukla, P.
  -  Baker, T.
  -  Sawin, V. I.
  -  Norris, S. L.
  -  Lewnard, J. A.
doi: https://doi.org/10.1016/j.epidem.2022.100570
page-layout: article
---
[[Back to Journal Club](../journal_club.qmd)]{.aside}

**Contribution and quality of mathematical modeling evidence in World Health Organization guidelines: A systematic review**

**Context**: For the first journal club, we will discuss a systematic review which identifies and assesses WHO guideline recommendations that include evidence from mathematical modeling studies. The goal is to take a high-level view of the relationship between modeling studies and actual public health practice.

Please read the journal club paper and come prepared to discuss your thoughts.

**Leader**: 

#### Learning Objectives

* Understand benefits and limitations of using mathematical modeling studies to guide global health policy  
* List important ethical considerations of using modeling to inform policy  
* Learn how modelers can ensure studies are conducted and reported in a rigorous & transparent manner  
* Become familiar with examples of mathematical modeling applied to global health policy

#### Guiding Questions

1. Modeling-informed recommendations were more likely to be conditional (versus strong), and to be based on evidence that was assessed as lower quality. Why might this be?  
2. How does reporting model limitations and assumptions affect trust in model validity?  
3. How does the use of mathematical modeling differ for infectious disease vs other disease guidelines?