---
title: "Journal Club 8: Cross-Model Comparisons"
author: 
  -  Penny, M. A. 
  -  Verity, R. 
  -  Bever, C. A. 
  -  et al. 
doi: https://www.sciencedirect.com/science/article/pii/S0140673615007254
page-layout: article
---
[[Back to Journal Club](../journal_club.qmd)]{.aside}

**Public health impact and cost-effectiveness of the RTS, S/AS01 malaria vaccine: a systematic comparison of predictions from four mathematical models**

**Context**: This week we are covering other malaria models, so we will discuss a paper that looks at the impact and cost-effectiveness of a novel intervention (the RTS,S vaccine) across four mathematical models - including EMOD. 

Please read the journal club paper and recommended additional reading, and come prepared to discuss your thoughts. If you are facilitating the session, prepare an overview of the paper and at least four guiding questions.

**Leader**:

#### Learning Objectives

* Understand the strengths and limitations of the different models used to assess the impact of RTS,S  
* Critically evaluate the specific assumptions and parameters used by each model, and how these may affect their predictions  
* Provide reasons for comparing predictions from multiple models

#### Guiding Questions

1.  
2.  
3.  
4.  

#### Recommended further reading

-  Smith, N.R., Trauer, J.M., Gambhir, M. et al. [Agent-based models of malaria transmission: a systematic review](https://doi.org/10.1186/s12936-018-2442-y). Malar J 17, 299 (2018).

