---
title: "Event Reports"
weight: 3
format: 
  html:
    toc: true
    toc-depth: 5
    page-layout: full
editor: 
  markdown: 
    wrap: 72
---

⚠️ How-To: report on broadcast events that occur during simulations

EMOD is capable of tracking a variety of built-in events as well as
custom campaign events. Custom events can be particularly useful for
explicitly tracking and counting the number of interventions
distributed. For example, in the simple SMC intervention (see How-To on
drug campaigns) we defined an event called `'Received_SMC'` to describe
children who actually received SMC drugs in the simulation. The
`add_health_seeking` function automatically generates a
`'Received_Treatment'` event for each individual receiving treatment for
symptomatic malaria. Adding custom events to the config parameter
`'Custom_Individual_Events'` is handled automatically.

# ReportEventCounter

To track how many events are occurring each day, request
`ReportEventCounter` and specify the list of events you would like to
track:

``` python
# Example
```

This generates a ReportEventCounter.json file that reports that total
number of events in each day of the simulation. Reporting a subset of
node IDs, restricting on age, and restricing on individual property are
all configurable. The format of the .json is identical to
InsetChart.json, so analyzers written for InsetChart.json can be easily
adapted for ReportEventCounter.

# ReportEventRecorder

Sometimes you may want to track individual-level events. To do so, we
use `ReportEventRecorder`, which is similar to `ReportEventCounter` but
lists each event as it occurs and provides information about the person
experiencing the event.

1.  Update configuration parameters

    ``` python
    #Example
    ```

There are additional optional parameters that you can specify to refine
your report: see full list
[here](https://docs.idmod.org/projects/emod-malaria/en/latest/software-report-event-recorder.html).
This can help reduce file sizes and speed up processing if you know
you'll only a subset of the simulation data.

After running, a file called ReportEventRecorder.csv will be generated
in the output/ folder for the simulation. Each row of the report
represents a distinct event, with the following information in its
columns:

-   Event Details:

    -   Time (when did event occur)
    -   Node_ID (where did event occur)
    -   Event_Name (what happened)

-   Individual Details (who did it happen to?):

    -   Individual_ID
    -   Age
    -   Gender
    -   Infected (1 = True)
    -   Infectiousness
    -   RelativeBitingRate
    -   TrueParasiteDensity
    -   TrueGametocyteDensity
    -   Plus an additional column for the value of each additional
        Individual Property included in the
        `'Report_Event_Recorder_Individual_Properties'` list.
