---
title: "FAQ"
weight: 1
format: 
  html: 
    toc: true
    toc-depth: 5
---

Answers to frequently asked questions about the program.

# For Interested Applicants

## Eligibility & Applications

#### Am I eligible to participate?

#### I can't travel to the United States. Can I participate?

#### How do I apply?

#### How much does it cost to apply?

#### I'm not eligible for the program / can't attend. How can I learn to use EMOD for malaria modeling?

## Funding

#### How much does the program cost?

#### How can I get funding to support my participation in the program?

# For Current Participants

## Logistics

#### When does the program start?

#### What are the pre-program requirements?

#### Where will I live and work during the program?

#### How do I register for ASTMH?

## Program Milestones

#### What is expected from each oral presentation?

#### What does it mean to 'facilitate' journal club?

# For Program Alumni

#### Who can I contact for help now that I have completed the program?

#### How can I help with future iterations of the program?

# General

#### How can I get involved?

#### How did this program start?
