---
title: "How-To: Demographics"
format: 
  html:
    toc: true
    toc-depth: 5
    page-layout: full
---

# Create a demographics file

The demographics file is a required input file for EMOD that specifies characteristics of the population in a simulation. This includes aspects like the population size, birth rates, non-malaria mortality rates, age structure, initial prevalence, and more. Full documentation on the demographics file can be found here.

At least one demographics file is required for every simulation unless you set the parameter Enable_Demographics_Builtin to 1 (one) in the configuration file. This setting does not represent a real location and is generally only used for testing and validating code.

For many applications, users often will reuse a standard demographics file and make modifications by hand or by script. In more complex simulations, creating a demographics file from scratch may be needed.

<details>

<p>

<summary><em>Parts of demographics file</em></summary>

A demographics file is a JSON file organized into 4 main sections:

1.  Metadata
2.  NodeProperties
3.  Defaults
    -   Parameters applied to all nodes in the simulation
4.  Nodes: each node is a simulated location. Transmission within a node is well-mixed, and nodes are connected by human and/or vector migration.
    -   Allows node-specific parameters
    -   Specified parameters override values in 'Defaults'

``` python
# Structure of Demographics File for a simulation with 1 node
  {
     "Metadata": {
          "DateCreated": "dateTime",
          "Tool": "scriptUsedToGenerate",
          "Author": "author",
          "IdReference": "Gridded world grump2.5arcmin",
          "NodeCount": "1"
     },
     "NodeProperties": [
          {...}
     ],
     "Defaults": {
          "NodeAttributes": {
            ...
            "BirthRateSource": "World Bank",
            "CountryBirthRate": 31.047,
            "World Bank Year": "2016",
            ...
          },
          "IndividualAttributes": {...},
          "IndividualProperties": {...}
     },
     "Nodes": [{
          "NodeID": 1,
          "NodeAttributes": {
            "BirthRate": 0.1190,
            "InitialPopulation": 1400,
            "Village": "Obom"
          },
          "IndividualAttributes": {...},
          "IndividualProperties": {...}
     }]
  }
```

</p>

</details>

<details>

<p>

<summary><em>Creating a demographics file</em></summary>

First, create a file "my_node.csv" with the following columns:

| Required                   | optional                                                                            |
|----------------------------|-------------------------------------------------------------------------------------|
| nodeid (unique \# \>0)     | Other node-specific variables, if any, such as village name, latitude, and logitude |
| population (starting size) |                                                                                     |

Example:

| nodeid | population | Village | lat      | lon        |
|--------|------------|---------|----------|------------|
| 1      | 1000       | "Obom"  | 5.760759 | -0.4473415 |

In EMODpy, we generate the demographics file for each simulation using a standard `build_demog()` function.

``` python
def build_demog():
    """
    This function builds a demographics input file for the DTK using emod_api.
    """
    
    # From template node #
    ######################
    # This snippet allows you to manually specify the node details instead of using a .csv
#    demog = Demographics.from_template_node(lat=1, lon=2, pop=1000, name="Example_Site")

    # From input file csv #
    #######################
    demog = Demographics.from_csv(input_file = os.path.join(<path_to_file>,"my_node.csv"),
                                  id_ref="indie_clusters", 
                                  init_prev = 0.01, 
                                  include_biting_heterogeneity = True)
    
    demog.SetEquilibriumVitalDynamics()
    age_distribution = Distributions.AgeDistribution_SSAfrica
    demog.SetAgeDistribution(age_distribution)

    return demog
```

</p>

</details>

### Create multi-node simulations

<details>

<p>

<summary>

<em>1. Generate Demographics</em>

<summary>

To run simultaneous simulations in multiple nodes, create an input file "my_nodes.csv" with one row for each node.

Ex. "my_nodes.csv"

| nodeid | lat   | lon   | population |
|--------|-------|-------|------------|
| 1      | 12.11 | -1.47 | 1000       |
| 2      | 12.03 | -1.44 | 1000       |
| 3      | 12.13 | -1.59 | 1000       |
| 17     | 12.06 | -1.48 | 1000       |

::: callout-note
# Note

-   Node IDs must be positive whole numbers, but do not have to be sequential
-   lat/lon values should represent real places with climates suitable for malaria transmission (if weather files are generated from demographics)
:::

Then, you can generate demographics for each node in every simulation, by adding this code to `build_demog()`

``` python
def build_demog():
    """
    This function builds a demographics input file for the DTK using emod_api.
    """
    
    # From template node #
    ######################
    # This snippet allows you to manually specify the node details instead of using a .csv
#    demog = Demographics.from_template_node(lat=1, lon=2, pop=1000, name="Example_Site")

    # From input file csv #
    #######################
    demog = Demographics.from_csv(input_file = os.path.join(<path_to_file>,"my_nodes.csv"),
                                  id_ref='spatial_example', 
                                  init_prev = 0.01, 
                                  include_biting_heterogeneity = True)
    
    demog.SetEquilibriumVitalDynamics()
    age_distribution = Distributions.AgeDistribution_SSAfrica
    demog.SetAgeDistribution(age_distribution)

    return demog
```

</p>

</details>

<details>

<p>

<summary>

<em>2. Set Node-Specific Parameters</em>

<summary>

Sometimes we want to vary properties between nodes based on prior knowledge. For any `NodeAttribute` parameters, these can be created simply by specifying them in the `my_nodes.csv` as columns and setting `load_other_columns_as_attributes=True` in the call to `DemographicsGenerator()`.

To set `IndividualAttributes` or `IndividualProperties`, see the following example. Imagine we know the proportion of "high-risk" individuals in each node and want to use this designation to target them for an intervention.

First, we would add a column to our input file representing the high-risk proportion in each node.

Ex. "my_nodes.csv"

| nodeid | lat   | lon   | population | high_risk |
|--------|-------|-------|------------|-----------|
| 1      | 12.11 | -1.47 | 1000       | 0.05      |
| 2      | 12.03 | -1.44 | 1000       | 0.10      |
| 3      | 12.13 | -1.59 | 1000       | 0.15      |
| 17     | 12.06 | -1.48 | 1000       | 0.50      |

Then, when we can assign the "high_risk" property to individuals in each node with the probability listed in the table, by adding the following code to the end of the generate_demographics() function definition, before writing the .json file.

::: callout-caution
## Coming Soon
:::

</p>

</details>

### Set up migration between nodes

Multi-node simulations allow for the possibility that humans or vectors will move between nodes. EMOD allows 6 migration types for humans (Local, Regional, Sea, Air, Family, and campaign) and two for vectors (Local and Regional). Other than the campaign type, all other migration types are set via input files and scaling factors in config.json, and these migration rates will remain the same throughout the simulation: we will call these "ongoing migration" to distinguish from the "forced migration" that is set via campaigns.

Multiple migration modes can be used for each agent type (human or vector) simultaneously. For example, we can set up a simulation using Local, Sea, and campaign migration for humans and Local and Regional migration for vectors.

#### Ongoing Migration

<details>

<p>

<summary>

<em>Human Migration Example</em>

<summary>

</p>

</details>

<details>

<p>

<summary>

<em>Vector Migration Example</em>

<summary>

</p>

</details>

#### Forced Migration

<details>

<p>

<summary>

<em>A Single Migration Event</em>

<summary>

</p>

</details>

<details>

<p>

<summary>

<em>Periodic Migration</em>

<summary>

</p>

</details>

<details>

<p>

<summary>

<em>Permanent Moves</em>

<summary>

</p>

</details>
